### ISSUE TITLE
Modwire 3 v1_2 boards for DIO connected to Transceiver reset issue

### ISSUE THREAD

**Issue by ghost** [oresat/low-gain-radio#15]
On the v1_2 boards the SPI status line was connected to the Transceiver reset by mistake. We can fix this then keep playing with the SPI interface software.

**Comment by ghost** [comment]
- Board A modwire complete and passes test.
- Board B failed test
- Board C awaiting modwire

**Comment by andrewgreenberg** [comment]
I'm closing this because we're moving on to v2_0.
