### ISSUE TITLE
DC blocking caps or critical filter components?

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/low-gain-radio#18]
C14 and C25 look like DC blocking caps. They were 100nF and 10nF respectively, both of which are really too big for good 0402 RF performance at 500+ MHz. So I switched them to 100 pF. Is that OK?

On that note:

What about removing C23, C58 or C61? Do we need C61 to protect the radio? Can we just remove all of these caps?

**Comment by glennl** [comment]
Yes, C14 and C25 sure look like DC blocks, and 100 pF seems fine. Go with it.

C23, C58, and C61 totally need to be there. They are blocking the DC associated with the PIN switch. They are all needed.

BTW, the insertion loss on the RF3025 is about 0.45 dB at 500 MHz. Sad.
