### ISSUE TITLE
Do not connect DIO0 to RESET(RF)

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/low-gain-radio#2]
v1.2 of the LGR has DIO0 connected to RESET(RF). Turns out DIO0's default configuration is to go high when a packet is transmitted, which means the whole transceiver is reset when a packet is sent.

Whoops. :/

In the future, don't do this. Use a regular GPIO pin.

**Comment by heathjake** [comment]
Connected now to PTE16.
