### ISSUE TITLE
Inverter for RF switch (NC7SZ05) output

### ISSUE THREAD

**Issue by wrh2** [oresat/low-gain-radio#5]
The selected inverter for the RF switch has high impedance open-drain output when input is low which means the RF switch doesn't switch to the LNA for RX. We've modwired a pull-up resistor for now but this component should be replaced.

**Comment by andrewgreenberg** [comment]
That said, because of available voltages and the switching voltage into the RXTX switch.

**Comment by heathjake** [comment]
We'll probably get rid of the current switch and use one that doesn't require an inverter so I'm closing this.
