### ISSUE TITLE
Get a new RXTX switch

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/low-gain-radio#6]
... one that can accept a control voltage that isn't "3.0V" but can accept a wider range, like 3.3 or even V+. Also, maybe one that doesn't blow up at 5V.

**Comment by heathjake** [comment]
http://www.psemi.com/pdf/datasheets/pe42723ds.pdf.

This is my suggested switch. Works at our frequency and has similar characteristics to the SkyWorks part. Also has the correct footprint and allows up to 3.6 V for the VCNT pin.

**Comment by wrh2** [comment]
http://www.rfmd.com/store/downloads/dl/file/id/28477/rf3025_data_sheet.pdf

Ended up going with this for the new rev.
